### ISSUE TITLE
As a developer, I want to make limitations on the author fields, to ensure that they contain what is intended.

### ISSUE THREAD

**Issue by thor2818** [ITU-BDSA23-GROUP23/Chirp#109]
Acceptance criteria:
- Author email needs to start with some letters and/or numbers, followed by a '@', then letters and/or numbers, followed by a '.', followed by some letters.
   - Use onModelCreation

**Comment by DHLarsen** [comment]
[Outdated, email is not accessible from github]

**Comment by thor2818** [comment]
Reopened as we kept Email in there, for future use.
